language: node_js
node_js:
  - 12.13.1

notifications:
  webhooks: https://coveralls.io/webhook

matrix:
    include:
        - env: COVERALLS_PARALLEL=true TARGET=client COVERALLS_FLAG_NAME=client
        - env: COVERALLS_PARALLEL=true TARGET=backend COVERALLS_FLAG_NAME=backend

install:
  - cd $TARGET
  - yarn --frozen-lockfile
script:
  - yarn test-coverage
after_script:
  - yarn submit-coverage
