language: node_js
node_js:
  - 12.13.1

matrix:
    include:
        - env: TARGET=client
        - env: TARGET=backend

install:
  - cd $TARGET
  - yarn --frozen-lockfile
script:
  - yarn test-coverage
